export const authUser_Url  = "http://localhost:8080/api/v1/customer/login"
export const getAllProducts_Url  = "http://localhost:8080/api/v1/products/getAllProducts"
export const editProduct_Url = "http://localhost:8080/api/v1/products/editProduct"
export const deleteProduct_Url = "http://localhost:8080/api/v1/products/deleteProduct"
export const addCategories_Url = "http://localhost:8080/api/v1/products/addCategory"
